
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ArrowLeft, Download, BarChart3, TrendingUp, Target, CheckCircle, AlertCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface InterviewAnalysisProps {
  onBack: () => void;
  sessionData?: any;
}

export const InterviewAnalysis = ({ onBack, sessionData }: InterviewAnalysisProps) => {
  const { toast } = useToast();

  const handleExportReport = () => {
    const reportContent = `
INTERVIEW ANALYSIS REPORT
========================

Session Overview:
- Date: ${new Date().toLocaleDateString()}
- Duration: 25 minutes
- Industry: Software Engineering
- Level: Mid Level
- Type: Technical Interview

Performance Summary:
- Overall Score: 85/100
- Communication: 90/100
- Technical Knowledge: 82/100
- Problem Solving: 88/100
- Professional Presence: 85/100

Detailed Analysis:
=================

STRENGTHS:
• Excellent communication skills and clear articulation
• Strong problem-solving approach with systematic thinking
• Good use of technical terminology and concepts
• Professional demeanor throughout the interview
• Provided specific examples to support answers
• Demonstrated confidence in core technical areas
• Used structured approach to answer behavioral questions

AREAS FOR IMPROVEMENT:
• Consider discussing time complexity more thoroughly
• Practice explaining complex concepts in simpler terms
• Work on providing more concrete examples for behavioral questions
• Improve confidence when discussing unfamiliar topics
• Prepare more diverse examples for STAR method responses
• Review advanced system design concepts
• Practice whiteboard coding under time pressure

DETAILED FEEDBACK:
=================

Technical Skills Assessment:
The candidate demonstrated strong technical knowledge with a solid understanding of software engineering principles. Code implementation was clean and well-structured. However, there's room for improvement in discussing algorithmic complexity and scalability considerations.

Communication Skills:
Excellent verbal communication with clear explanations. The candidate articulated thoughts well and maintained good eye contact. Responses were well-organized and easy to follow.

Problem-Solving Approach:
Showed systematic thinking and good analytical skills. Approached problems methodically, breaking them down into manageable parts. Could benefit from more detailed explanation of thought process.

Behavioral Responses:
Used STAR method effectively for most behavioral questions. Examples were relevant and demonstrated leadership potential. Would benefit from preparing more diverse scenarios.

RECOMMENDATIONS:
===============

Immediate Actions (Next 1-2 weeks):
1. Practice system design questions focusing on scalability
2. Review time and space complexity for common algorithms
3. Prepare 5-7 additional STAR method examples
4. Practice explaining technical concepts to non-technical audiences

Medium-term Goals (Next 1-2 months):
1. Complete mock interview sessions with peers or mentors
2. Study advanced data structures and algorithms
3. Practice whiteboard coding regularly
4. Improve knowledge of distributed systems concepts

Long-term Development (Next 3-6 months):
1. Seek leadership opportunities in current role
2. Contribute to open-source projects
3. Stay updated with industry trends and best practices
4. Build portfolio projects demonstrating technical skills

NEXT STEPS:
==========

1. Schedule follow-up practice sessions focusing on identified weak areas
2. Review common behavioral questions and prepare structured responses
3. Practice technical concepts with emphasis on clear explanation
4. Continue regular interview practice to maintain and improve skills
5. Seek feedback from mentors and peers on communication style

SCORING BREAKDOWN:
=================

Communication (90/100):
- Clear articulation: Excellent
- Professional tone: Excellent
- Listening skills: Very Good
- Question clarification: Good

Technical Knowledge (82/100):
- Core concepts: Very Good
- Problem-solving: Very Good
- Code quality: Good
- System design: Needs Improvement

Professional Presence (85/100):
- Confidence: Very Good
- Engagement: Excellent
- Professionalism: Excellent
- Time management: Good

Overall Assessment:
The candidate shows strong potential with solid technical skills and excellent communication abilities. With focused preparation on identified areas, they should perform well in future interviews.

Generated by Neuro Ask Interview Practice Platform
Report Date: ${new Date().toLocaleString()}
Session ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `neuro-ask-interview-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Exported Successfully",
      description: "Your detailed interview analysis report has been downloaded as a text file.",
    });
  };

  const analysisData = {
    overallScore: 85,
    scores: {
      communication: 90,
      technical: 82,
      problemSolving: 88,
      presence: 85
    },
    strengths: [
      "Excellent communication skills and clear articulation",
      "Strong problem-solving approach with systematic thinking",
      "Good use of technical terminology and concepts",
      "Professional demeanor throughout the interview",
      "Provided specific examples to support answers"
    ],
    improvements: [
      "Consider discussing time complexity more thoroughly",
      "Practice explaining complex concepts in simpler terms",
      "Work on providing more concrete examples for behavioral questions",
      "Improve confidence when discussing unfamiliar topics"
    ]
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-gray-900 to-black relative overflow-hidden page-enter">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-1/2 -right-1/2 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute -bottom-1/2 -left-1/2 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-cyan-500/5 rounded-full blur-2xl animate-float"></div>
        <div className="absolute top-3/4 right-1/4 w-48 h-48 bg-indigo-500/5 rounded-full blur-2xl animate-pulse-slow"></div>
      </div>

      <div className="relative z-10">
        <div className="container mx-auto px-6 py-8 max-w-6xl">
          {/* Header */}
          <div className="flex items-center justify-between mb-8 fade-in">
            <div className="flex items-center">
              <Button 
                variant="ghost" 
                onClick={onBack} 
                className="mr-4 text-white/90 hover:text-white hover:bg-white/10 backdrop-blur-sm border border-white/10"
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Dashboard
              </Button>
              <div>
                <h1 className="text-3xl font-bold text-white mb-2 text-reveal">Interview Analysis</h1>
                <p className="text-white/80 text-reveal">Detailed performance analysis and recommendations</p>
              </div>
            </div>
            <Button 
              onClick={handleExportReport}
              className="bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600 text-white shadow-lg"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Report
            </Button>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Main Analysis */}
            <div className="lg:col-span-2 space-y-6">
              {/* Overall Score */}
              <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                <CardHeader>
                  <CardTitle className="flex items-center text-white">
                    <BarChart3 className="h-5 w-5 mr-2 text-cyan-400" />
                    Overall Performance
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-center mb-6">
                    <div className="text-5xl font-bold text-white mb-2">{analysisData.overallScore}</div>
                    <div className="text-cyan-200">out of 100</div>
                  </div>
                  <div className="grid md:grid-cols-2 gap-4">
                    {Object.entries(analysisData.scores).map(([key, score]) => (
                      <div key={key} className="space-y-2">
                        <div className="flex justify-between">
                          <span className="text-white/90 capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                          <span className="text-blue-300 font-semibold">{score}%</span>
                        </div>
                        <Progress value={score} className="bg-white/20" />
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Strengths */}
              <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                <CardHeader>
                  <CardTitle className="flex items-center text-white">
                    <CheckCircle className="h-5 w-5 mr-2 text-green-400" />
                    Strengths
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {analysisData.strengths.map((strength, index) => (
                      <div key={index} className="flex items-start space-x-3 fade-in">
                        <CheckCircle className="h-5 w-5 text-green-400 mt-0.5 flex-shrink-0" />
                        <p className="text-white/90">{strength}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Areas for Improvement */}
              <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                <CardHeader>
                  <CardTitle className="flex items-center text-white">
                    <Target className="h-5 w-5 mr-2 text-orange-400" />
                    Areas for Improvement
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {analysisData.improvements.map((improvement, index) => (
                      <div key={index} className="flex items-start space-x-3 fade-in">
                        <AlertCircle className="h-5 w-5 text-orange-400 mt-0.5 flex-shrink-0" />
                        <p className="text-white/90">{improvement}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              {/* Quick Stats */}
              <Card className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 backdrop-blur-md border border-blue-500/30 hover:from-blue-500/25 hover:to-cyan-500/25 transition-all duration-300 card-entrance">
                <CardHeader>
                  <CardTitle className="text-white">Session Details</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-white/80">Duration:</span>
                    <span className="font-medium text-white">25 minutes</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Questions:</span>
                    <span className="font-medium text-white">8 answered</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Industry:</span>
                    <span className="font-medium text-white">Software Engineering</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Level:</span>
                    <span className="font-medium text-white">Mid Level</span>
                  </div>
                </CardContent>
              </Card>

              {/* Recommendations */}
              <Card className="bg-gradient-to-br from-purple-500/20 to-pink-500/20 backdrop-blur-md border border-purple-500/30 hover:from-purple-500/25 hover:to-pink-500/25 transition-all duration-300 scale-in">
                <CardHeader>
                  <CardTitle className="text-white">Next Steps</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3 text-sm">
                    <div className="p-3 bg-white/10 backdrop-blur-sm rounded-lg border border-white/20">
                      <p className="font-medium text-white mb-1">Practice System Design</p>
                      <p className="text-white/80">Focus on scalability and architecture questions</p>
                    </div>
                    <div className="p-3 bg-white/10 backdrop-blur-sm rounded-lg border border-white/20">
                      <p className="font-medium text-white mb-1">Behavioral Questions</p>
                      <p className="text-white/80">Prepare more STAR method examples</p>
                    </div>
                    <div className="p-3 bg-white/10 backdrop-blur-sm rounded-lg border border-white/20">
                      <p className="font-medium text-white mb-1">Mock Interviews</p>
                      <p className="text-white/80">Schedule regular practice sessions</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
