import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { ArrowLeft, Download, BarChart3, TrendingUp, Target, CheckCircle, AlertCircle } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";

interface InterviewAnalysisProps {
  onBack: () => void;
  sessionId: string;
}

export const InterviewAnalysis = ({ onBack, sessionId }: InterviewAnalysisProps) => {
  const { toast } = useToast();
  const [loading, setLoading] = useState(true);
  const [session, setSession] = useState<any | null>(null);

  useEffect(() => {
    const fetchSession = async () => {
      setLoading(true);
      const { data, error } = await supabase
        .from('practice_sessions')
        .select('*')
        .eq('id', sessionId)
        .single();
      if (error) {
        toast({ title: "Error", description: "Failed to load interview session.", variant: "destructive" });
        setSession(null);
      } else {
        setSession(data);
      }
      setLoading(false);
    };
    if (sessionId) fetchSession();
  }, [sessionId, toast]);

  const handleExportReport = () => {
    if (!session) return;
    const strengths = Array.isArray(session.strengths) ? session.strengths : [];
    const weaknesses = Array.isArray(session.weaknesses) ? session.weaknesses : [];
    const recommendations = Array.isArray(session.recommendations) ? session.recommendations : [];
    const improvements = Array.isArray(session.improvements) ? session.improvements : [];
    const reportContent = `
INTERVIEW ANALYSIS REPORT
========================

Session Overview:
- Date: ${new Date(session.completed_at || session.created_at).toLocaleDateString()}
- Duration: ${Math.round((session.duration_seconds || 0) / 60)} minutes
- Industry: ${session.industry || "N/A"}
- Level: ${session.level || "N/A"}
- Type: ${session.type || session.session_type || "N/A"}

Performance Summary:
- Overall Score: ${session.overall_score || 0}/100
- Communication: ${session.skill_breakdown?.communication || 0}/100
- Technical Knowledge: ${session.skill_breakdown?.technical_knowledge || 0}/100
- Problem Solving: ${session.skill_breakdown?.problem_solving || 0}/100
- Cultural Fit: ${session.skill_breakdown?.cultural_fit || 0}/100

Strengths:
${strengths.length > 0 ? strengths.map((s: string) => `• ${s}`).join('\n') : 'No strengths recorded.'}

Areas for Improvement:
${(weaknesses.length > 0 ? weaknesses : improvements).length > 0 ? (weaknesses.length > 0 ? weaknesses : improvements).map((w: string) => `• ${w}`).join('\n') : 'No improvements recorded.'}

Recommendations:
${recommendations.length > 0 ? recommendations.map((r: string) => `• ${r}`).join('\n') : 'No recommendations recorded.'}

Detailed Feedback:
${session.detailed_feedback || "No feedback available."}

Generated by Neuro Ask Interview Practice Platform
Report Date: ${new Date().toLocaleString()}
Session ID: ${session.id}
    `;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `neuro-ask-interview-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Exported Successfully",
      description: "Your detailed interview analysis report has been downloaded as a text file.",
    });
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4"></div>
        <p className="text-white/70">Loading interview analysis...</p>
      </div>
    );
  }

  if (!session) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-red-400">Interview session not found.</p>
        <Button onClick={onBack} className="mt-4">Back</Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-gray-900 to-black relative overflow-hidden page-enter">
      {/* Animated Background Elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-1/2 -right-1/2 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute -bottom-1/2 -left-1/2 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse-slow"></div>
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-cyan-500/5 rounded-full blur-2xl animate-float"></div>
        <div className="absolute top-3/4 right-1/4 w-48 h-48 bg-indigo-500/5 rounded-full blur-2xl animate-pulse-slow"></div>
      </div>

      <div className="relative z-10">
        <div className="container mx-auto px-6 py-8 max-w-6xl">
          {/* Header */}
          <div className="flex items-center justify-between mb-8 fade-in">
            <div className="flex items-center">
              <Button 
                variant="ghost" 
                onClick={onBack} 
                className="mr-4 text-white/90 hover:text-white hover:bg-white/10 backdrop-blur-sm border border-white/10"
              >
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Dashboard
              </Button>
              <div>
                <h1 className="text-3xl font-bold text-white mb-2 text-reveal">Interview Analysis</h1>
                <p className="text-white/80 text-reveal">Detailed performance analysis and recommendations</p>
              </div>
            </div>
            <Button 
              onClick={handleExportReport}
              className="bg-gradient-to-r from-cyan-500 to-blue-500 hover:from-cyan-600 hover:to-blue-600 text-white shadow-lg"
            >
              <Download className="h-4 w-4 mr-2" />
              Export Report
            </Button>
          </div>

          <div className="grid lg:grid-cols-3 gap-8">
            {/* Main Analysis */}
            <div className="lg:col-span-2 space-y-6">
              {/* Overall Score */}
              <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                <CardHeader>
                  <CardTitle className="flex items-center text-white">
                    <BarChart3 className="h-5 w-5 mr-2 text-cyan-400" />
                    Overall Performance
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="text-center mb-6">
                    <div className="text-5xl font-bold text-white mb-2">{session.overall_score || 0}</div>
                    <div className="text-cyan-200">out of 100</div>
                  </div>
                  <div className="grid md:grid-cols-2 gap-4">
                    {session.skill_breakdown && Object.entries(session.skill_breakdown).map(([key, score]) => (
                      <div key={key} className="space-y-2">
                        <div className="flex justify-between">
                          <span className="text-white/90 capitalize">{key.replace(/_/g, ' ')}</span>
                          <span className="text-blue-300 font-semibold">{typeof score === 'number' ? `${score}%` : 'N/A'}</span>
                        </div>
                        <Progress value={typeof score === 'number' ? score : 0} className="bg-white/20" />
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>

              {/* Strengths */}
              {Array.isArray(session.strengths) && session.strengths.length > 0 ? (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <CheckCircle className="h-5 w-5 mr-2 text-green-400" />
                      Strengths
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {session.strengths.map((strength: string, index: number) => (
                        <div key={index} className="flex items-start space-x-3 fade-in">
                          <CheckCircle className="h-5 w-5 text-green-400 mt-0.5 flex-shrink-0" />
                          <p className="text-white/90">{strength}</p>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <CheckCircle className="h-5 w-5 mr-2 text-green-400" />
                      Strengths
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-white/70">No strengths recorded.</div>
                  </CardContent>
                </Card>
              )}

              {/* Areas for Improvement */}
              {Array.isArray(session.weaknesses) && session.weaknesses.length > 0 ? (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <Target className="h-5 w-5 mr-2 text-orange-400" />
                      Areas for Improvement
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {session.weaknesses.map((improvement: string, index: number) => (
                        <div key={index} className="flex items-start space-x-3 fade-in">
                          <AlertCircle className="h-5 w-5 text-orange-400 mt-0.5 flex-shrink-0" />
                          <p className="text-white/90">{improvement}</p>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ) : Array.isArray(session.improvements) && session.improvements.length > 0 ? (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <Target className="h-5 w-5 mr-2 text-orange-400" />
                      Areas for Improvement
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {session.improvements.map((improvement: string, index: number) => (
                        <div key={index} className="flex items-start space-x-3 fade-in">
                          <AlertCircle className="h-5 w-5 text-orange-400 mt-0.5 flex-shrink-0" />
                          <p className="text-white/90">{improvement}</p>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <Target className="h-5 w-5 mr-2 text-orange-400" />
                      Areas for Improvement
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-white/70">No improvements recorded.</div>
                  </CardContent>
                </Card>
              )}

              {/* Recommendations */}
              {Array.isArray(session.recommendations) && session.recommendations.length > 0 ? (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <TrendingUp className="h-5 w-5 mr-2 text-blue-400" />
                      Recommendations
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="space-y-3">
                      {session.recommendations.map((rec: string, index: number) => (
                        <div key={index} className="flex items-start space-x-3 fade-in">
                          <TrendingUp className="h-5 w-5 text-blue-400 mt-0.5 flex-shrink-0" />
                          <p className="text-white/90">{rec}</p>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <TrendingUp className="h-5 w-5 mr-2 text-blue-400" />
                      Recommendations
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-white/70">No recommendations recorded.</div>
                  </CardContent>
                </Card>
              )}

              {/* Detailed Feedback */}
              {session.detailed_feedback ? (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20 hover:bg-white/15 transition-all duration-300 slide-up">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <BarChart3 className="h-5 w-5 mr-2 text-cyan-400" />
                      Detailed Feedback
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-white/80 text-sm whitespace-pre-line">
                      {session.detailed_feedback}
                    </div>
                  </CardContent>
                </Card>
              ) : (
                <Card className="bg-white/10 backdrop-blur-md border border-white/20">
                  <CardHeader>
                    <CardTitle className="flex items-center text-white">
                      <BarChart3 className="h-5 w-5 mr-2 text-cyan-400" />
                      Detailed Feedback
                    </CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-white/70">No feedback available.</div>
                  </CardContent>
                </Card>
              )}
            </div>

            {/* Sidebar */}
            <div className="space-y-6">
              {/* Quick Stats */}
              <Card className="bg-gradient-to-br from-blue-500/20 to-cyan-500/20 backdrop-blur-md border border-blue-500/30 hover:from-blue-500/25 hover:to-cyan-500/25 transition-all duration-300 card-entrance">
                <CardHeader>
                  <CardTitle className="text-white">Session Details</CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-white/80">Duration:</span>
                    <span className="font-medium text-white">{Math.round((session.duration_seconds || 0) / 60)} minutes</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Questions:</span>
                    <span className="font-medium text-white">{session.questions_answered || 0} answered</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Industry:</span>
                    <span className="font-medium text-white">{session.industry || "N/A"}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-white/80">Level:</span>
                    <span className="font-medium text-white">{session.level || "N/A"}</span>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
