// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkfkmzgekxmczxhfxsey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrZmttemdla3htY3p4aGZ4c2V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTU4NjYsImV4cCI6MjA2ODA3MTg2Nn0.DkSrvX2xjI-gVwJE3KSr7l0qeIG7oYejtW2_csusy7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});